version: '3'

networks:
  laravel:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - laravel

  # php
  php-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  # mysql
  mysql_service:
    image: mysql:5.7
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
    networks:
      - laravel

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - php-service
      - mysql-service
    networks:
      - laravel



